(dev/drupal#79) Update PHP version checks
Overview
--------

If you install or upgrade CiviCRM 5.16+ on PHP 5.x, then it produces a syntax error:

```
Error: syntax error, unexpected ':', expecting '{' in <...>/civicrm/vendor/league/csv/src/functions.php, line 33
```

It is correct to raise an error, but the error should be more digestable -- i.e. telling the user that their
version of PHP is in compatible.

Comments
--------

This patch has two parts:

* Pro-forma changes to existing PHP version checks (s/5.3.4/7.0.0/)
* An additional check which addresses some scenario (installer?) which was still had the ugly error

I started working on this patch after doing a dozen similar PRs for the
different repos+branches, and I finally conked out in civicrm-joomla after
the 4th iteration of re-running distmaker.  I'm pretty sure this is better
than before, but I ran out patience and suspect there are still some
scenarios producing the uglier message.